AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DYNAMO_TABLE:
          Ref: GGDynamoTemplateSimpleTable
        DB_ENDPOINT: http://dynamodb.eu-west-1.amazonaws.com
        REGION_NAME: eu-west-1
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://catchphrase-api/4284828161ccd99cf2cebccc43128a92
      Handler: app.getHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /list
            Method: get
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: GGDynamoTemplateSimpleTable
  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://catchphrase-api/cc4b4cf5a767c0211e58dbbe31d0a6aa
      Handler: app.postHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /add
            Method: post
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: GGDynamoTemplateSimpleTable
  GGDynamoTemplateSimpleTable:
    Type: AWS::Serverless::SimpleTable
    TableName: giphy-guess-table
    PrimaryKey:
      Name: id
      Type: String
    Tags:
      AppType: Serverless
