AWSTemplateFormatVersion: '2010-09-09'
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Api:
    Cors:
      AllowHeaders: '''Content-Type'''
      AllowMethods: '''OPTIONS,POST,GET'''
      AllowOrigin: '''*'''
  Function:
    Environment:
      Variables:
        DB_ENDPOINT: http://dynamodb.eu-west-1.amazonaws.com
        DYNAMO_TABLE:
          Ref: DataStoreTable
        REGION_NAME: eu-west-1
    Timeout: 3
Resources:
  DataStoreTable:
    PrimaryKey:
      Name: id
      Type: String
    TableName: giphy-guess-table-name
    Tags:
      AppType: Serverless
    Type: AWS::Serverless::SimpleTable
  DeleteFunction:
    Properties:
      CodeUri: s3://catchphrase-api/984288fcea3161713e2858940f06114f
      Events:
        HelloWorld:
          Properties:
            Method: post
            Path: /delete
          Type: Api
      Handler: app.deleteHandler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DataStoreTable
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  GetFunction:
    Properties:
      CodeUri: s3://catchphrase-api/b564052de2bddf9f7c3f3e06ea4e0e05
      Events:
        HelloWorld:
          Properties:
            Method: get
            Path: /list
          Type: Api
      Handler: app.getHandler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DataStoreTable
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  PostFunction:
    Properties:
      CodeUri: s3://catchphrase-api/09dfe66d1a5bcc6fea88a1d780e7e1d9
      Events:
        HelloWorld:
          Properties:
            Method: post
            Path: /add
          Type: Api
      Handler: app.postHandler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DataStoreTable
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
