AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DYNAMO_TABLE:
          Ref: DataStoreTable
        DB_ENDPOINT: http://dynamodb.eu-west-1.amazonaws.com
        REGION_NAME: eu-west-1
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://catchphrase-api/377b733e6ab21234be930e2c6a27f690
      Handler: app.getHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /list
            Method: get
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DataStoreTable
  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://catchphrase-api/a16006fc3749d8d3138a5fb569d3a648
      Handler: app.postHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /add
            Method: post
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DataStoreTable
  DataStoreTable:
    Type: AWS::Serverless::SimpleTable
    TableName: giphy-guess-table-name
    PrimaryKey:
      Name: id
      Type: String
    Tags:
      AppType: Serverless
