AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DYNAMO_TABLE:
          Ref: DataStoreTable
        DB_ENDPOINT: http://dynamodb.eu-west-1.amazonaws.com
        REGION_NAME: eu-west-1
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://catchphrase-api/f569205593b035c780ba03e69b093894
      Handler: app.getHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /list
            Method: get
            cors: true
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DataStoreTable
  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://catchphrase-api/e8db97650a609d7ca393edf6557f343c
      Handler: app.postHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /add
            Method: post
            cors: true
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DataStoreTable
  DataStoreTable:
    Type: AWS::Serverless::SimpleTable
    TableName: giphy-guess-table-name
    PrimaryKey:
      Name: id
      Type: String
    Tags:
      AppType: Serverless
