AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Api:
    Cors:
      AllowMethods: '''OPTIONS,POST,GET'''
      AllowHeaders: '''Content-Type'''
      AllowOrigin: '''*'''
  Function:
    Timeout: 3
    Environment:
      Variables:
        DYNAMO_TABLE:
          Ref: DataStoreTable
        DB_ENDPOINT: http://dynamodb.eu-west-1.amazonaws.com
        REGION_NAME: eu-west-1
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://catchphrase-api/ef7a68611ce8b84ce895727cef136b41
      Handler: app.getHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /list
            Method: get
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DataStoreTable
  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://catchphrase-api/088d29edb5efeca3e4d67aacfb86e16e
      Handler: app.postHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /add
            Method: post
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DataStoreTable
  DataStoreTable:
    Type: AWS::Serverless::SimpleTable
    TableName: giphy-guess-table-name
    PrimaryKey:
      Name: id
      Type: String
    Tags:
      AppType: Serverless
